import math

PREDEFINED_ACCURACY = 0.91    # 规定精度
GLOBAL_UPDATE_FREQUENCY = 5   # 同步轮次
BATCH_SIZE = 32

# 基础配置
TOTAL_CPUS   = 56
TOTAL_SERVER_A_CPUS =  32 # ServerA总CPU数
TOTAL_SERVER_B_CPUS = TOTAL_CPUS - TOTAL_SERVER_A_CPUS # ServerB总CPU数
WORKER_NUM = 5
WORKER_A_NUM = WORKER_NUM  # ServerA的worker数量
WORKER_B_NUM = WORKER_NUM  # ServerB的worker数量

# 限制server最大CPU数为1
MAX_SERVER_CPUS = 2

# Server A的CPU分配
SERVER_A_CPUS = min(MAX_SERVER_CPUS, TOTAL_SERVER_A_CPUS // (WORKER_A_NUM + 1))
REMAINING_A_CPUS = TOTAL_SERVER_A_CPUS - SERVER_A_CPUS
WORKER_A_CPUS = math.floor(REMAINING_A_CPUS / WORKER_A_NUM)

# Server B的CPU分配
SERVER_B_CPUS = min(MAX_SERVER_CPUS, TOTAL_SERVER_B_CPUS // (WORKER_B_NUM + 1))
REMAINING_B_CPUS = TOTAL_SERVER_B_CPUS - SERVER_B_CPUS
WORKER_B_CPUS = math.floor(REMAINING_B_CPUS / WORKER_B_NUM)


NOISE_MULTIPLIER = 0.1
