import math

PREDEFINED_ACCURACY = 0.92    #规定精度
GLOBAL_UPDATE_FREQUENCY = 5   #同步轮次
BATCH_SIZE = 32
# 基础配置
TOTAL_CPUS = 64
TOTAL_SERVER_A_CPUS = 4 # ServerA总CPU数
TOTAL_SERVER_B_CPUS = TOTAL_CPUS -TOTAL_SERVER_A_CPUS  # ServerB总CPU数
WORKER_NUM = 5
WORKER_A_NUM = WORKER_NUM  # ServerA的worker数量
WORKER_B_NUM = WORKER_NUM  # ServerB的worker数量

# 计算每个组件的CPU数 (向下取整)
WORKER_A_CPUS = math.floor(TOTAL_SERVER_A_CPUS / (WORKER_A_NUM + 1))
SERVER_A_CPUS = TOTAL_SERVER_A_CPUS - (WORKER_A_NUM * WORKER_A_CPUS)
WORKER_B_CPUS = math.floor(TOTAL_SERVER_B_CPUS / (WORKER_B_NUM + 1))
SERVER_B_CPUS = TOTAL_SERVER_B_CPUS - (WORKER_B_NUM * WORKER_B_CPUS)